/**
 * =====================================================================
 * FRAGENKATALOG (SlideEffect)
 * =====================================================================
 * 13 recherchierte Frage-Antwort-Sets aus der Quellen-Dokumentation
 * =====================================================================
 */

const QUESTION_POOL = [
  {
    id: 1,
    question: "Wie viel operativen Gewinn (in US-Dollar) hat OpenAI im Jahr 2025 gemacht?",
    unit: "Mrd. $",
    min: -40,
    max: 40,
    step: 1,
    actual: -21,
    actualDisplay: "-21 Mrd. US-Dollar (Verlust)",
    explanation: "OpenAI machte 2025 trotz rund 13 Mrd. US-Dollar Umsatz einen operativen Verlust von etwa 21 Mrd. US-Dollar.",
    sourceName: "Financial Times / Ed Zitron, zusammengefasst bei Digitec",
    sourceDate: "2026",
    sourceUrl: "https://www.digitec.ch/de/page/geleakte-zahlen-zeigen-openai-schreibt-gigantische-verluste-43044"
  },
  {
    id: 2,
    question: "Wie viel Nettogewinn (in US-Dollar) hat Meta im Jahr 2025 gemacht?",
    unit: "Mrd. $",
    min: 0,
    max: 100,
    step: 0.1,
    actual: 60.5,
    actualDisplay: "60,5 Mrd. US-Dollar",
    explanation: "Meta erzielte 2025 einen Gesamtumsatz von 200,97 Mrd. US-Dollar und einen Nettogewinn von 60,46 Mrd. US-Dollar (gerundet 60,5 Mrd. $).",
    sourceName: "Meta Platforms, Inc., Full Year 2025 Results",
    sourceDate: "28.01.2026",
    sourceUrl: "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-Fourth-Quarter-and-Full-Year-2025-Results/"
  },
  {
    id: 3,
    question: "Wie viele Stunden Videomaterial werden bei YouTube durchschnittlich pro Minute hochgeladen?",
    unit: "Stunden",
    min: 0,
    max: 800,
    step: 10,
    actual: 500,
    actualDisplay: "500 Stunden / Minute",
    explanation: "Auf YouTube werden durchschnittlich mehr als 500 Stunden Videomaterial pro Minute hochgeladen – das entspricht rund 82 Jahren Videomaterial pro Tag. Dieser Wert ist seit etwa 2019 stabil.",
    sourceName: "YouTube Blog, 'Reimagining video infrastructure to empower YouTube'",
    sourceDate: "2021",
    sourceUrl: "https://blog.youtube/inside-youtube/new-era-video-infrastructure/"
  },
  {
    id: 4,
    question: "Wie viele Snaps werden weltweit durchschnittlich pro Minute auf Snapchat erstellt?",
    unit: "Mio. Snaps/Min",
    min: 0,
    max: 5,
    step: 0.1,
    actual: 3.8,
    actualDisplay: "3,8 Mio. Snaps / Min",
    explanation: "2025 wurden auf Snapchat fast 2 Billionen Snaps erstellt – durchschnittlich 5,5 Milliarden pro Tag bzw. rund 3,8 Millionen Snaps pro Minute.",
    sourceName: "Snap Inc. Newsroom",
    sourceDate: "2026",
    sourceUrl: "https://newsroom.snap.com/2trillion-snaps-in-2025"
  },
  {
    id: 5,
    question: "Wie viele neue TikTok-Videos entstehen schätzungsweise pro Tag?",
    unit: "Mio. Videos/Tag",
    min: 0,
    max: 50,
    step: 0.5,
    actual: 28.5,
    rangeMin: 23,
    rangeMax: 34,
    actualDisplay: "23 – 34 Mio. Videos/Tag",
    explanation: "Auf TikTok entstehen schätzungsweise 23 bis 34 Millionen neue Videos pro Tag. TikTok veröffentlicht selbst keine offizielle Zahl zu den täglichen Uploads; die Angabe basiert auf unabhängigen Schätzungen.",
    sourceName: "Socialrails",
    sourceDate: "2025 (aktualisiert 2026)",
    sourceUrl: "https://socialrails.com/blog/how-many-videos-uploaded-daily-statistics"
  },
  {
    id: 6,
    question: "Wie viel Prozent des weltweiten Games-Umsatzes 2025 entfielen auf Mobile Games?",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    actual: 56.2,
    actualDisplay: "56,2 %",
    explanation: "Der globale Games-Umsatz lag 2025 bei 201,6 Mrd. US-Dollar. Davon entfielen 113,3 Mrd. US-Dollar auf Mobile Games (rund 56,2 % des Gesamtmarktes), 43,6 Mrd. auf PC und 44,7 Mrd. auf Konsole.",
    sourceName: "Newzoo, Global Games Market Report 2025",
    sourceDate: "2026",
    sourceUrl: "https://newzoo.com/articles/global-games-market-2025"
  },
  {
    id: 7,
    question: "Wie viel Prozent des weltweiten Online-Traffics 2025 stammten von Bots und waren somit nicht-menschlichen Ursprungs?",
    unit: "%",
    min: 0,
    max: 100,
    step: 1,
    actual: 53,
    actualDisplay: "53 %",
    explanation: "Im Jahr 2025 war mehr als die Hälfte des weltweiten Web-Traffics automatisiert: über 53 % stammten von Bots und anderen automatisierten Systemen. Weniger als die Hälfte des Traffics war menschlich.",
    sourceName: "Imperva (Thales), Bad Bot Report",
    sourceDate: "2026",
    sourceUrl: "https://www.imperva.com/blog/bad-bot-report-2026-bots-agentic-age/"
  },
  {
    id: 8,
    question: "Wie viele User erreicht Meta täglich weltweit über seine Dienste?",
    unit: "Mrd. User/Tag",
    min: 0,
    max: 8,
    step: 0.01,
    actual: 3.58,
    exactTolerance: 0.1,
    actualDisplay: "3,58 Mrd. User/Tag",
    explanation: "Im Dezember 2025 nutzten weltweit durchschnittlich 3,58 Milliarden Menschen täglich mindestens einen Dienst der Meta-Familie (Facebook, Instagram, WhatsApp) – 7 % mehr als im Vorjahr. 97,6 % des Meta-Umsatzes stammten aus Werbung.",
    sourceName: "Meta Platforms, Inc., Fourth Quarter and Full Year 2025 Results",
    sourceDate: "2026",
    sourceUrl: "https://investor.atmeta.com/investor-news/press-release-details/2026/Meta-Reports-Fourth-Quarter-and-Full-Year-2025-Results/"
  },
  {
    id: 9,
    question: "Wie viel Prozent der User eines Free-to-Play-Spiels erzielen rund 90 % des Umsatzes ('Whales')?",
    unit: "%",
    min: 0,
    max: 100,
    step: 0.1,
    actual: 1.5,
    actualDisplay: "1,5 %",
    explanation: "Bei Free-to-Play-Spielen kann sich der Umsatz extrem auf wenige User konzentrieren. In einer wissenschaftlichen Untersuchung eines Mobile-Games erzielten nur 1,5 % der User ganze 90 % des Umsatzes. Diese User werden als 'Whales' bezeichnet.",
    sourceName: "Amano & Simonov, 'What Makes Players Pay?' (U.S. FTC)",
    sourceDate: "2024",
    sourceUrl: "https://www.ftc.gov/system/files/ftc_gov/pdf/simonovamano.pdf"
  },
  {
    id: 10,
    question: "Wie viele Minuten sind Jugendliche (12–19 Jahre) durchschnittlich täglich am Handy?",
    unit: "Minuten",
    min: 0,
    max: 400,
    step: 1,
    actual: 231,
    actualDisplay: "231 Minuten (ca. 3,8 Std.)",
    explanation: "Die durchschnittliche Smartphone-Bildschirmzeit von Jugendlichen (12–19 Jahre) beträgt 231 Minuten pro Tag. 74 % nutzen KI-Anwendungen für Hausaufgaben oder zum Lernen (2024: 65 %); die ChatGPT-Nutzung stieg von 57 % (2024) auf 84 % (2025).",
    sourceName: "mpfs – JIM-Studie 2025",
    sourceDate: "2025",
    sourceUrl: "https://mpfs.de/app/uploads/2025/11/JIM_2025_PDF_barrierearm.pdf"
  },
  {
    id: 11,
    question: "Wie groß ist die verfügbare Rechenkapazität (in GW) der Serverfarmen von OpenAI im Jahr 2025?",
    unit: "GW",
    min: 0,
    max: 5,
    step: 0.1,
    actual: 1.9,
    hasPowerComparison: true,
    actualDisplay: "1,9 GW",
    explanation: "OpenAI steigerte seine verfügbare Rechenkapazität von 0,2 GW (2023) auf rund 1,9 GW (2025) – fast das Zehnfache.\n\nVergleichswerte zur Einordnung:\n• 10 kW = Einfamilienhaus\n• 100 kW = Schule\n• 1 MW = Industriewerk\n• 100 MW = Große Wind- & Solarparks\n• 1 GW = Großes Kraftwerk (Kernkraft / Kohle)\n• Jedes weitere GW = Ein volles Großkraftwerk mehr!",
    sourceName: "OpenAI, 'A business that scales with the value of intelligence'",
    sourceDate: "2026",
    sourceUrl: "https://openai.com/de-DE/index/a-business-that-scales-with-the-value-of-intelligence/"
  },
  {
    id: 12,
    question: "Wie viel Nettogewinn (in US-Dollar) hat Alphabet (Mutterkonzern von Google) im Jahr 2025 gemacht?",
    unit: "Mrd. $",
    min: 0,
    max: 150,
    step: 0.1,
    actual: 132.2,
    actualDisplay: "132,2 Mrd. US-Dollar",
    explanation: "Alphabet erzielte 2025 erstmals 402,8 Milliarden US-Dollar Umsatz und einen Nettogewinn von 132,2 Milliarden US-Dollar – gut eine Viertel Million Dollar reiner Gewinn pro Minute!",
    sourceName: "SEC-Jahresbericht (Form 10-K), Alphabet Inc.",
    sourceDate: "2026",
    sourceUrl: "https://www.sec.gov/Archives/edgar/data/1652044/000165204426000018/goog-20251231.htm"
  },
  {
    id: 13,
    question: "Wie viele Suchanfragen verarbeitet Google rechnerisch pro Minute?",
    unit: "Mio. Anfragen/Min",
    min: 0,
    max: 15,
    step: 0.1,
    actual: 9.5,
    actualDisplay: "9,5 Mio. Suchanfragen / Min",
    explanation: "Google verarbeitet mehr als 5 Billionen Suchanfragen pro Jahr – rechnerisch mehr als 9,5 Millionen Suchanfragen pro Minute.",
    sourceName: "Google Blog, Google Marketing Live 2025",
    sourceDate: "2025",
    sourceUrl: "https://blog.google/products/ads-commerce/google-marketing-live-2025/"
  }
];
